# This workflow action performs code analysis over the repo to ensure safety from build failures
# as well as security faults

name: Code Analysis

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  analyze:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Code Analysis
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      # Setup Build Environment
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: java

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4

      # Build Java Project
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: build

      # Analyze Source Code
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
