# This workflow action performs code analysis over the repo to ensure safety from build failures
# as well as security faults

name: Code Analysis

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  analyze:
    name: Code Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      # Setup Build Environment
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4

      # Build Java Project
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.2.1
        with:
          arguments: build
          cache-disabled: true

      # Analyze Source Code
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
